[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache"

[[redirects]]
  from = "/supabase-api/*"
  to = "https://oxalbyjhvqbdwnbdrpwv.supabase.co/:splat"
  status = 200
  force = true
